# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03de7c60250fd21e615dc777a037b321f4599db0a2436c9589e1a237ee4accff83e31bd19d610e9523d8354dc47447995c4d9408cee35e1a1430d67773bde2fe

test:
  secret_key_base: f54609c34da4ce91efb93c23b045aeee0ff651416a8c175abe84aaa7f9e83236141c50a1852ab13212392365d20158ebc486c9a30c5dda5b57b1107b61dae124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
